//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.ProfileDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class ProfileDataSource { }
#else

	public class ProfileDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public ProfileDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SteamyWP7;component/SampleData/ProfileDataSource/ProfileDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Eid = string.Empty;

		public string Eid
		{
			get
			{
				return this._Eid;
			}

			set
			{
				if (this._Eid != value)
				{
					this._Eid = value;
					this.OnPropertyChanged("Eid");
				}
			}
		}

		private System.Windows.Media.ImageSource _Thumbnail = null;

		public System.Windows.Media.ImageSource Thumbnail
		{
			get
			{
				return this._Thumbnail;
			}

			set
			{
				if (this._Thumbnail != value)
				{
					this._Thumbnail = value;
					this.OnPropertyChanged("Thumbnail");
				}
			}
		}

		private double _Gender = 0;

		public double Gender
		{
			get
			{
				return this._Gender;
			}

			set
			{
				if (this._Gender != value)
				{
					this._Gender = value;
					this.OnPropertyChanged("Gender");
				}
			}
		}

		private double _Age = 0;

		public double Age
		{
			get
			{
				return this._Age;
			}

			set
			{
				if (this._Age != value)
				{
					this._Age = value;
					this.OnPropertyChanged("Age");
				}
			}
		}

		private System.Windows.Media.ImageSource _Picture = null;

		public System.Windows.Media.ImageSource Picture
		{
			get
			{
				return this._Picture;
			}

			set
			{
				if (this._Picture != value)
				{
					this._Picture = value;
					this.OnPropertyChanged("Picture");
				}
			}
		}

		private string _Link = string.Empty;

		public string Link
		{
			get
			{
				return this._Link;
			}

			set
			{
				if (this._Link != value)
				{
					this._Link = value;
					this.OnPropertyChanged("Link");
				}
			}
		}

		private double _Rating = 0;

		public double Rating
		{
			get
			{
				return this._Rating;
			}

			set
			{
				if (this._Rating != value)
				{
					this._Rating = value;
					this.OnPropertyChanged("Rating");
				}
			}
		}

		private double _Votes = 0;

		public double Votes
		{
			get
			{
				return this._Votes;
			}

			set
			{
				if (this._Votes != value)
				{
					this._Votes = value;
					this.OnPropertyChanged("Votes");
				}
			}
		}

		private double _Percentile = 0;

		public double Percentile
		{
			get
			{
				return this._Percentile;
			}

			set
			{
				if (this._Percentile != value)
				{
					this._Percentile = value;
					this.OnPropertyChanged("Percentile");
				}
			}
		}

		private string _Emid = string.Empty;

		public string Emid
		{
			get
			{
				return this._Emid;
			}

			set
			{
				if (this._Emid != value)
				{
					this._Emid = value;
					this.OnPropertyChanged("Emid");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
